### ISSUE TITLE
JSONDecodeError: Invalid control character

### ISSUE THREAD

**Issue by avp90** [jazzpi/sundtek-to-xmltv#2]
I got the following error after `sh run-grabber.sh`:
```
Traceback (most recent call last):
  File "./sundtek-grab.py", line 44, in <module>
    data.append(r.json())
  File "/home/pi/.local/lib/python3.5/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 1 column 10919 (char 10918)
```

Do you have a idea or should I debug by myself?

**Comment by avp90** [comment]
I can reproduce it sometimes. 😄 
```
Traceback (most recent call last):
  File "D:\GIT\DVBCServer\sundtek-to-xmltv\test.local.py", line 4, in <module>
    __import__('sundtek-grab.py')
  File "D:\GIT\DVBCServer\sundtek-to-xmltv\sundtek-grab.py", line 188, in <module>
    parse_channels_shows(overviews)
  File "D:\GIT\DVBCServer\sundtek-to-xmltv\sundtek-grab.py", line 146, in parse_channels_shows
    shows[event_id] = get_show_data(service_id, event_id, delsys)
  File "D:\GIT\DVBCServer\sundtek-to-xmltv\sundtek-grab.py", line 108, in get_show_data
    data = r.json()
  File "C:\Program Files\Python37\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by avp90** [comment]
fixed with last commit
