### ISSUE TITLE
ValueError: astimezone() cannot be applied to a naive datetime

### ISSUE THREAD

**Issue by avp90** [jazzpi/sundtek-to-xmltv#4]
I get the following error after `sh run-grabber.sh`:
```
Traceback (most recent call last):
  File "./sundtek-grab.py", line 94, in <module>
    shows[event_id] = show_data(service_id, event_id, delsys)
  File "./sundtek-grab.py", line 64, in show_data
    start = format_time(details[0])
  File "./sundtek-grab.py", line 51, in format_time
    dt = datetime.datetime.utcfromtimestamp(timestamp).astimezone(tz)
ValueError: astimezone() cannot be applied to a naive datetime
```

**Comment by avp90** [comment]
i fixed it with:  
```python
import pytz
...
def format_time(timestamp):
    dt = pytz.utc.localize(datetime.datetime.utcfromtimestamp(timestamp))
```
